import {onCall,HttpsError} from 'firebase-functions/v2/https';
import {onUserCreated} from 'firebase-functions/v2/identity';
import {initializeApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore,FieldValue} from 'firebase-admin/firestore';
import {randomUUID} from 'crypto';
initializeApp(); const db=getFirestore();
const ADMIN_EMAIL='rahihumaun369@gmail.com';
const requireUser=(req:any)=>{if(!req.auth)throw new HttpsError('unauthenticated','Please sign in.');return req.auth.uid};
export const grantOwnerClaim=onUserCreated(async e=>{if(!e.data)return;const email=e.data.email?.toLowerCase()||'';if(email===ADMIN_EMAIL)await getAuth().setCustomUserClaims(e.data.uid,{admin:true});await db.doc(`users/${e.data.uid}`).set({name:e.data.displayName||'',email:e.data.email||'',createdAt:FieldValue.serverTimestamp()},{merge:true});});
export const ensureAdminClaim=onCall(async req=>{const uid=requireUser(req);const u=await getAuth().getUser(uid);if(u.email?.toLowerCase()!==ADMIN_EMAIL)throw new HttpsError('permission-denied','Not authorized.');await getAuth().setCustomUserClaims(uid,{...(u.customClaims||{}),admin:true});return {ok:true};});
const admin=async(req:any)=>{const uid=requireUser(req);const u=await getAuth().getUser(uid);if(u.customClaims?.admin!==true)throw new HttpsError('permission-denied','Admin access required.');return uid;};
export const createOrder=onCall(async req=>{const uid=requireUser(req);const {items,customer,paymentMethod,transactionId=''}=req.data||{};if(!Array.isArray(items)||!items.length)throw new HttpsError('invalid-argument','Cart is empty.');if(!customer?.name||!customer?.phone||!customer?.address||!customer?.area)throw new HttpsError('invalid-argument','Complete the checkout fields.');if(!['Cash on Delivery','bKash','Nagad'].includes(paymentMethod))throw new HttpsError('invalid-argument','Invalid payment method.');if(paymentMethod!=='Cash on Delivery'&&!transactionId)throw new HttpsError('invalid-argument','Transaction ID is required.');
 const orderRef=db.collection('orders').doc();let total=0,subtotal=0;const cleanItems:any[]=[];await db.runTransaction(async tx=>{for(const raw of items){const productRef=db.doc(`products/${raw.productId}`);const ps=await tx.get(productRef);if(!ps.exists)throw new HttpsError('not-found','A product is no longer available.');const p=ps.data()!;const qty=Number(raw.quantity);if(!Number.isInteger(qty)||qty<1)throw new HttpsError('invalid-argument','Invalid quantity.');if((p.stock??0)<qty)throw new HttpsError('failed-precondition',`Insufficient stock for ${p.name}.`);if(p.visibility!==true)throw new HttpsError('failed-precondition',`${p.name} is unavailable.`);const sizes=p.availableSizes||[];const colors=p.availableColors||[];if(sizes.length&&!sizes.includes(raw.selectedSize))throw new HttpsError('invalid-argument','Invalid size.');if(colors.length&&!colors.includes(raw.selectedColor))throw new HttpsError('invalid-argument','Invalid color.');const unit=Number(p.discountedPrice);if(!Number.isFinite(unit)||unit<0)throw new HttpsError('failed-precondition','Invalid product price.');const line=unit*qty;subtotal+=line;cleanItems.push({productId:raw.productId,productName:p.name,productImage:p.images?.[0]||'',selectedSize:raw.selectedSize||'',selectedColor:raw.selectedColor||'',quantity:qty,originalPrice:Number(p.originalPrice),discountPercentage:Number(p.discountPercentage||0),finalUnitPrice:unit,lineTotal:line});tx.update(productRef,{stock:FieldValue.increment(-qty),updatedAt:FieldValue.serverTimestamp()});}
 const delivery=customer.area==='Moulvibazar'?50:150;total=subtotal+delivery;tx.set(orderRef,{customerId:uid,customerEmail:req.auth.token.email||'',customerName:String(customer.name),phone:String(customer.phone),address:String(customer.address),area:String(customer.area),items:cleanItems,subtotal,voucherDiscount:0,deliveryCharge:delivery,total,paymentMethod,transactionId:paymentMethod==='Cash on Delivery'?'':String(transactionId),status:'Pending',createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});for(const raw of items)tx.delete(db.doc(`users/${uid}/cart/${raw.id}`));});await db.collection('activityLogs').add({customerId:uid,type:'order_created',orderId:orderRef.id,createdAt:FieldValue.serverTimestamp()});return {ok:true,orderId:orderRef.id,total};});
export const setOrderStatus=onCall(async req=>{await admin(req);const {orderId,status}=req.data||{};if(!orderId||!['Pending','Confirmed','Delivered','Cancelled'].includes(status))throw new HttpsError('invalid-argument','Invalid order update.');await db.doc(`orders/${orderId}`).update({status,updatedAt:FieldValue.serverTimestamp()});return {ok:true};});
export const claimDailyQuiz=onCall(async req=>{const uid=requireUser(req);const {questionId,answer}=req.data||{};if(!questionId)throw new HttpsError('invalid-argument','Question required.');const settings=(await db.doc('settings/site').get()).data()||{};if(settings.quizEnabled===false)throw new HttpsError('failed-precondition','Quiz is disabled.');const qref=db.doc(`quizQuestions/${questionId}`);const q=await qref.get();if(!q.exists||q.data()?.active!==true)throw new HttpsError('not-found','Question unavailable.');const today=new Date();const key=today.toISOString().slice(0,10);const attempt=db.doc(`users/${uid}/quizAttempts/${key}`);const hist=db.doc(`users/${uid}/quizQuestionHistory/${questionId}`);if((await attempt.get()).exists)throw new HttpsError('already-exists','You already attempted today.');if((await hist.get()).exists)throw new HttpsError('failed-precondition','That question was already used for this customer.');const correct=answer===q.data()?.correctAnswer;await db.runTransaction(async tx=>{tx.create(attempt,{questionId,answer,correct,createdAt:FieldValue.serverTimestamp()});tx.create(hist,{usedAt:FieldValue.serverTimestamp()});if(correct){const v=db.collection(`users/${uid}/vouchers`).doc();const now=Date.now();tx.set(v,{voucherId:v.id,customerId:uid,amount:2,source:'Quiz',createdAt:FieldValue.serverTimestamp(),expiry:new Date(now+60*24*60*60*1000),usageCount:0,maxUsage:3,productUsage:{},status:'active'});}});await db.collection('activityLogs').add({customerId:uid,type:'quiz_attempt',questionId,correct,createdAt:FieldValue.serverTimestamp()});return {correct,reward:correct?2:0};});
export const claimWeeklyReward=onCall(async req=>{const uid=requireUser(req);const settings=(await db.doc('settings/site').get()).data()||{};if(settings.weeklyRewardEnabled===false)throw new HttpsError('failed-precondition','Weekly reward is disabled.');const week=new Date();const key=`${week.getUTCFullYear()}-${String(Math.ceil((((week.getTime()-new Date(Date.UTC(week.getUTCFullYear(),0,1)).getTime())/86400000)+new Date(Date.UTC(week.getUTCFullYear(),0,1)).getUTCDay()+1)/7)).padStart(2,'0')}`;const ref=db.doc(`users/${uid}/weeklyClaims/${key}`);if((await ref.get()).exists)throw new HttpsError('already-exists','Already claimed this week.');const n=Math.floor(Math.random()*1000)+1;let amount:number;if(n<=800)amount=Math.floor(Math.random()*5)+1;else if(n<=995)amount=Math.floor(Math.random()*5)+6;else if(n===996)amount=11;else if(n===997)amount=15;else if(n===998)amount=20;else if(n===999)amount=50;else amount=80;const v=db.collection(`users/${uid}/vouchers`).doc();await db.runTransaction(async tx=>{tx.create(ref,{claimedAt:FieldValue.serverTimestamp(),voucherId:v.id});tx.set(v,{voucherId:v.id,customerId:uid,amount,source:'Weekly Reward',createdAt:FieldValue.serverTimestamp(),expiry:new Date(Date.now()+60*24*60*60*1000),usageCount:0,maxUsage:3,productUsage:{},status:'active'});});return {amount};});
